// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using VirtoCommerce.AssetsModule.Data.Repositories;

namespace VirtoCommerce.AssetsModule.Data.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20000000000000_UpdateAssetsV3")]
    partial class UpdateAssetsV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VirtoCommerce.AssetsModule.Data.Model.AssetEntryEntity", b =>
            {
                b.Property<string>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(128)")
                    .HasMaxLength(128);

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(64)")
                    .HasMaxLength(64);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Group")
                    .HasColumnType("nvarchar(64)")
                    .HasMaxLength(64);

                b.Property<string>("LanguageCode")
                    .HasColumnType("nvarchar(10)")
                    .HasMaxLength(10);

                b.Property<string>("MimeType")
                    .HasColumnType("nvarchar(128)")
                    .HasMaxLength(128);

                b.Property<string>("ModifiedBy")
                    .HasColumnType("nvarchar(64)")
                    .HasMaxLength(64);

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(1024)")
                    .HasMaxLength(1024);

                b.Property<string>("RelativeUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(2083)")
                    .HasMaxLength(2083);

                b.Property<long>("Size")
                    .HasColumnType("bigint");

                b.Property<string>("TenantId")
                    .HasColumnType("nvarchar(128)")
                    .HasMaxLength(128);

                b.Property<string>("TenantType")
                    .HasColumnType("nvarchar(256)")
                    .HasMaxLength(256);

                b.HasKey("Id");

                b.HasIndex("RelativeUrl", "Name")
                    .HasName("IX_AssetEntry_RelativeUrl_Name");

                b.ToTable("AssetEntry");
            });
#pragma warning restore 612, 618
        }
    }
}
